### ISSUE TITLE
Node.JS binding does not support PONG

### ISSUE THREAD

**Issue by atoikka** [qaap/uws-bindings#1]
Hi!

I would like to enquire about the Node.JS binding supporting sending the PONG frame (0x0A). Is it deliberate that it is missing or should it be added?

From the websockets/ws implementation, I see that it is present, but naturally I would love to use the more performant library.

Thanks!

**Comment by mkozjak** [comment]
Hi, @atoikka!

Since for rpc-websockets we've switched back to ws, we don't really support this repository, anymore. PRs welcome, though.

**Comment by atoikka** [comment]
Thanks for the info.

As for the reason for changing back to ws - is it related to the original author stopping development and dropping support for the Node.JS binding that may lead to instability downstream and not getting updates from uWS C++ base?

**Comment by mkozjak** [comment]
We simply do not support a behaviour of the original author. We also need certain features not available on uws. We would rather have a slower, but more stable and featureful dependency to ship our products.

**Comment by atoikka** [comment]
Alright, agreed about the behavior from what I see :) Thank you!

**Comment by mkozjak** [comment]
No problem! Thanks for reporting!
